export default [
    {
        id: '1',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '“아이들은 무엇을 생각해야 하는지가 아니라 어떻게 생각하는지 가르쳐야 합니다.”',
        footer: '마가렛 미드',
        description: '건축가(INTJ)는 합리성과 자제력으로 유명하며 이러한 강점을 공유하지 않는 사람(예: 어린이)은 누구나 어리둥절할 수 있습니다. 이러한 성격의 경우 양육은 종종 새로운 기술을 습득하고 인지적 유연성을 개발해야 합니다. 다행스럽게도 건축가는 거의 항상 도전에 직면해 있습니다. 자녀가 있는 건축가에게 부모가 되는 것은 특히 의미 있는 도전이 될 수 있습니다.',
        Characteristic1: '정직한 연결',
        Chdescriptsion1_1: '건축가는 자녀가 명확한 관심과 강력한 비판적 사고 능력을 갖추고 유능하고 자립할 수 있도록 성장하기를 바랍니다. 무의미한 규칙을 강요하기보다 이러한 성격 유형을 가진 부모는 자녀의 독립성을 키울 수 있는 연령에 적합한 방법을 찾습니다. 그렇다고 건축가가 관대하다는 말은 아닙니다. 그들은 자녀들이 그들의 자유를 책임감 있게 사용하기를 기대합니다.',
        Chdescriptsion1_2: '',
        typetext1: '건축가 부모는 자녀를 자신이 대우받고 싶은 대로 솔직하고 존중하며 대합니다.',
        Chdescriptsion1_3: '일부 성격 유형은 어려운 주제로부터 자녀를 보호할 수 있지만 건축가 부모는 지식이 무지보다 훨씬 낫다고 믿습니다. 그들에게 솔직함은 존경심을 표현하는 방법이며, 자녀를 현실로부터 보호하는 것은 실례가 될 것입니다.',
        Chdescriptsion1_4: '물론 이 접근 방식의 성공 여부는 이러한 어려운 사실에 대한 자녀의 준비 상태를 정확하게 측정하는 건축가의 능력에 달려 있습니다.',
        Characteristic2: '감정의 혼돈',
        Chdescriptsion2_1: '다른 많은 성격 유형과 비교할 때 건축가는 애정 표현에 특히 익숙하지 않습니다. 누군가에게 사랑과 칭찬으로 샤워하는 것은 그들에게 부자연스럽게 느껴질 수 있습니다. 그 "누군가"가 자신의 자녀일지라도 말입니다. 그러나 아이들은 특히 어린 시절에 껴안고 승인하고 다른 사랑의 표현이 필요합니다.',
        Chdescriptsion2_2: '결과적으로 건축가 부모는 자녀에게 자신이 얼마나 사랑받는지 보여주기 위해 정서적 안정 지대를 확장해야 할 수도 있습니다.',
        typetext2: '건축가는 문제의 근본 원인을 해결하기 위한 계획을 개발할 수 있을 때 최선을 다합니다. 그러나 때때로 아이의 문제에 대한 가장 좋은 해결책은 아이가 자신의 감정을 탐색할 때 아이와 함께 앉아 있는 것입니다.',
        Chdescriptsion2_3: '',
        Characteristic3: '인생의 도전을 위한 준비',
        Chdescriptsion3_1: '건축가는 자녀들이 인생이 그들에게 던지는 모든 것을 다룰 준비가 되어 있는지 확인하려고 노력합니다. 이 성격 유형을 가진 부모는 도전을 학습 기회로 재구성하는 재능이 있으며 그렇게 함으로써 자녀가 자신만의 합리적인 사고 및 문제 해결 스타일을 개발하도록 영감을 줄 수 있습니다. 시간이 지남에 따라 건축가의 자녀는 이러한 기술을 점점 더 복잡해지는 상황에 적용하여 성장하면서 자신감을 키울 수 있습니다.',
        Chdescriptsion3_2: '모든 부모는 자녀의 미래에 대한 다른 꿈을 가지고 있습니다. 건축가에게 꿈은 자신의 마음을 알고 문제를 해결하는 유능한 어른을 키우는 것입니다.',
        typetext3: '건축가는 인생의 모든 어렵거나 불쾌한 일로부터 자녀를 보호한다면 이런 일이 일어날 수 없다는 것을 이해합니다. ',
        Chdescriptsion3_3: '그러나 그들의 희망은 자녀에게 올바른 도구를 제공하면 그럴 필요가 없다는 것입니다.',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '2',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '많은 사회적 역할과 마찬가지로 육아에서 논리학자는 강력하지만 건전한 도전에 직면합니다. 때때로 그들은 아이들의 지저분하고 비합리적이며 끊임없이 변화하지만 완전히 자연스러운 감정에 당황할 수 있습니다. 결국, 아이들은 논리학자들이 당연하게 여기는 종류의 선택의지와 논리를 아직 발달시키지 못했습니다. 그러나 부모가 되는 것은 논리학자에게 매우 의미가 있습니다. 이러한 성격 유형을 가진 부모는 호기심과 배움에 대한 사랑으로 인해 자녀에게 세상에 대해 가르치는 데 큰 기쁨을 느낄 수 있습니다. 관대하고 개방적인 논리학자들은 자녀들이 독립적으로 생각하고, 새로운 지식을 찾고, 자신의 의견을 말하고 변호하도록 격려합니다.',
        Characteristic1: '자기 자신에게 진실하라',
        Chdescriptsion1_1: '이 성격 유형을 가진 부모는 사회적 기대에 대해 초조해하지 않습니다. 다시 말해서, 그들은 자녀가 어떻게 행동해야 하는지에 대한 양육 조언이나 다른 사람들의 생각에 거의 집착하지 않습니다. 그들은 또한 자녀를 학교 > 직업 > 결혼 > 집 > 자녀 > 은퇴의 전통적인 삶으로 밀어붙일 것 같지 않습니다(그리고 그 순서로 대단히 감사합니다).',
        Chdescriptsion1_2: '',
        typetext1: '논리학자들은 다른 사람들을 통제하는 데 거의 관심이 없습니다. 그들은 자녀가 자신의 원칙과 의견을 형성하도록 허용합니다. 그러나 만일을 대비하여 자신의 관점과 아이디어를 공유할 수도 있습니다.',
        Chdescriptsion1_3: '이것은 논리학자들이 자녀들에 대한 기대가 없다는 말은 아닙니다. 그들은 자녀가 스스로 동기를 부여하고 독립하기를 기대합니다. 그들은 자녀가 충분히 크면 자신의 삶의 길을 결정하고 그것을 따라갈 방법을 찾는 데 필요한 비판적 사고 능력을 갖기를 바랍니다.',
        Chdescriptsion1_4: '',
        Characteristic2: '자유의 선물',
        Chdescriptsion2_1: '논리학자는 아이들의 호기심을 북돋아 지식을 습득하고 시야를 넓힐 수 있는 자유를 줍니다. 이러한 부모는 일반적으로 자녀에게 편안하고 지적인 접근 방식을 취합니다. 불필요한 규칙이나 엄격한 일정을 강요하기보다는 탐색과 독립을 장려하는 가정 환경을 만드는 것을 목표로 합니다.',
        Chdescriptsion2_2: '논리적인 성격의 경우, 자녀의 독립성을 존중하는 것은 존경의 표시입니다. 그러나 많은 어린이들(심지어 젊은 성인들까지)에게 이러한 수준의 개인 자유는 벅찰 수 있습니다. 가정 생활에 합리적인 경계와 부모의 지도가 포함되지 않는 경우, 이 아이들은 자신이 세상을 스스로 이해해야 한다고 확신하며 집중력이 떨어지거나 방황할 수 있습니다. 참으로 어려운 일입니다.',
        typetext2: '역설적이게도, 로지션스의 자녀들이 독특하고 독립적인 자아로 꽃을 피우기 위해 필요한 것은 바로 돌봄 규칙과 부모의 확인이라는 안정적인 가정 기반이 될 수 있다는 것입니다.',
        Chdescriptsion2_3: '다행히도 논리학자는 너무 손을 떼지 않고도 자녀의 독립성을 격려할 수 있다는 것을 이해할 수 있는 정신적 유연성을 가지고 있습니다. 이러한 성격 유형을 가진 부모는 자녀가 필요할 때마다 조언과 지원을 제공할 수 있도록 함으로써 균형을 다시 잡을 수 있습니다. 그들은 또한 명확하고 상식적인 경계를 설정하고 잘못된 행동에 대한 합당한 결과를 설정하여 자녀가 자신의 급증하는 자제력에 전적으로 의존하지 않고 일상 생활을 탐색할 수 있도록 할 수 있습니다.',
        Characteristic3: '가치 있는 도전',
        Chdescriptsion3_1: '논리적인 부모에게 정서적 지원을 제공하는 것은 쉽지 않을 수 있습니다. 사실, 규칙과 경계를 설정하는 것과 함께 가장 큰 어려움 중 하나일 수 있습니다. 좋은 소식은 이러한 성격이 약간의 노력이 필요할지라도 이러한 도전을 해결할 수 있다는 것입니다.',
        Chdescriptsion3_2: '논리학자는 자녀가 자신의 문제를 해결하고 자신의 필요를 충족하도록 권한을 부여하기를 원합니다. 이것은 가치 있는 목표이지만, 아이들이 스스로 세상을 다루기 전에 앞서 언급한 규칙과 경계와 함께 검증과 지원의 꾸준한 기초가 필요합니다. 이러한 기반을 구축하는 데 도움이 되도록 Logician 부모는 자녀에 대해 느끼는 사랑과 애정, 감탄을 표현해야 합니다.',
        typetext3: '이성적인 논리를 가진 논리학자에게는 애정을 쏟아붓는 것이 어색하거나 과한 것처럼 보일 수 있지만 이러한 말과 행동은 아이들이 사랑받고 인정받고 안정감을 느끼도록 돕는 데 큰 도움이 됩니다.',
        Chdescriptsion3_3: '논리학자들은 자녀들이 똑똑하고 독립적으로 자라기를 바라는 것 외에는 아무 것도 없습니다. 이러한 성격 유형을 가진 부모가 합리성과 함께 공감을 가르치는 한, 자녀는 질문을 하고, 마음을 사용하고, 어떤 일이 닥치더라도 스스로를 돌볼 줄 아는 자신감 있는 성인으로 성장할 수 있습니다.',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '3',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '부모로서 대부분의 사령관은 자녀의 필요와 감정을 수용할 수 있는 공간을 마련하기 위해 자신의 강인하고 지나치게 논리적인 삶의 접근 방식을 조정해야 합니다.',
        Characteristic1: '',
        Chdescriptsion1_1: '이것은 결코 Commander 성격 유형을 가진 사람들이 나쁜 부모라는 것을 의미하지는 않습니다. 이는 일반적으로 더 민감하고 진정으로 이성적인 분석을 수행할 수 없는 자녀와의 관계가 훨씬 더 감정적인 재치와 개인적인 필요를 요구한다는 것입니다.',
        Chdescriptsion1_2: '그들이 주는 것에 익숙한 것보다 더 많은 자유를.',
        typetext1: '지휘관은 항상 도전을 준비하고 있으며 부모로서의 역할을 진지하게 받아들이고 개인적인 책임감을 가지고 최선을 다할 것입니다.',
        Chdescriptsion1_3: '대부분의 사람들보다 더 높은 표준에 자신을 붙들고 있는 커맨더 성격은 자녀의 성공을 그러한 개인 표준의 반영으로 보고, 자녀가 목표를 달성하기 위해 노력하는 똑똑하고 독립적인 사람으로 성장하는 것을 보는 것 이상을 원하지 않습니다.',
        Chdescriptsion1_4: '지휘관에게 특정한 도덕적 가치를 확립하는 것은 지성과 자주적이고 합리적인 사고를 함양하는 것보다 덜 중요합니다.',
        Characteristic2: '정서적 관용 구축',
        Chdescriptsion2_1: '지휘관은 의견의 차이를 환영하며 이는 자녀에게도 마찬가지입니다. 그러나 사령관은 역할과 책임에 대해 합리적이고 신중하게 논의하는 동안 기쁘게 생각하지만, 결국 지휘관은 자신의 권위가 존중되기를 기대합니다. 의견 불일치는 확립된 책임을 회피하는 데 대한 변명이 될 수 없으며 사령관 부모는 이 구조를 유지하는 데 있어 완전히 타협하지 않을 수 있습니다. 이러한 엄격함은 가정에 엄청난 긴장의 원인이 될 수 있습니다. 약간의 유연성은 큰 도움이 될 수 있습니다.',
        Chdescriptsion2_2: '이러한 논쟁이 감정적 호소로 발전할 때 사령관 부모는 정서적 관용에 대한 지속적인 약점이 성장하는 어린이, 특히 청소년을 다루는 것이 가장 중요한 도전이 되기 때문에 실제 문제에 부딪힐 때입니다. 다른 관계에서와 마찬가지로 Commander 부모는 이 기술을 강화하기 위해 노력해야 합니다. 종종 어린 아이들은 자신의 필요를 합리적으로 표현할 수 있는 단어가 없고 청소년은 완전히 자연스러운 상태인 인내심을 갖지 못합니다.',
        typetext2: '지휘관은 감정 표현에 귀를 기울이는 법을 배우고 친절하게 대응함으로써 자녀들과의 정서적 갈등을 최소화하고 반항적인 십대 시절을 부드럽게 만드는 데 도움이 되는 신뢰를 구축할 수 있습니다.',
        Chdescriptsion2_3: '',
        Characteristic3: '독립성 육성',
        Chdescriptsion3_1: '지휘관 부모는 필요한 독립심을 개발하기 위해 자신의 일정과 활동을 통제하고 자신의 진로를 계획할 수 있다는 것을 기억해야 합니다.',
        Chdescriptsion3_2: '',
        typetext3: '지휘관 성격의 사람들은 자녀를 위해 노력을 아끼지 않겠지만, 자녀가 성장하고 성숙함에 따라 심호흡을 하고 구조를 느슨하게 하는 것이 강제 과외보다 유능하고 지적인 성인을 키우는 목표를 달성하는 데 더 도움이 되는 경우가 있습니다. ',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '4',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '토론자들의 요란하고 날뛰는 성격은 양육을 그들에게 특별한 도전으로 만들 것이라고 생각할 수 있으며, 여러 면에서 그들이 옳을 것입니다. 그러나 토론자 성격 유형을 가진 사람들이 무엇보다 좋아하는 것 중 하나는 자신의 약점을 해결하는 것과 관련하여 해결해야 할 문제인 좋은 도전입니다. ',
        Chdescriptsion1_2: '. 토론자들은 부모로서의 역할을 진지하게 생각하며, 삶의 이러한 발전에 깊은 영향을 받을 수밖에 없습니다.',
        typetext1: '자녀와 같은 외부 영향을 받아 자신의 잘못을 해결하기 위해 그 영향력을 사용할 수 있는 사람이 있다면 바로 토론자입니다.',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '자유로운 사상가 키우기',
        Chdescriptsion2_1: '처음부터 토론자들의 규칙과 규정에 대한 혐오감은 분명하며, 그들은 어린 자녀들에게 스스로 탐구하는 데 필요한 자유를 줄 가능성이 높습니다. 독립은 토론자에게 가장 필요한 것 중 하나이며 독립적인 마음 없이는 완전한 사람은 없다고 생각합니다.',
        Chdescriptsion2_2: '',
        typetext2: '토론하는 성격은 단순히 안전하기 위해 설계된 무겁게 구조화된 환경이 아니라 열정과 이성의 발달을 통한 발견의 기쁨에 기초하여 자녀를 위한 편안하고 정통하지 않은 환경을 만듭니다.',
        Chdescriptsion2_3: '자녀가 성장하고 발달함에 따라 토론자는 자녀가 독립적으로 생각하고 반대, 의견 및 대안을 표명하도록 권장합니다. 그러나 자녀가 자신의 생각을 감정과 필요에 따라 표현하도록 격려하는 외교관 부모와 달리 토론자는 자녀가 이러한 선택에 공정하고 논리적인 입장에서 접근하여 기분을 좋게 만드는 것보다 효과적인 것이 무엇인지 설명하도록 가르칩니다. . 다른 관계에서와 마찬가지로 이러한 감정적 접근 불가능성은 토론자들이 고군분투하는 부분입니다.',
        Characteristic3: '',
        Chdescriptsion3_1: '자녀가 청소년기로 성장하고 건강한 감정 표현의 균형을 찾는 법을 배우면서 토론자 성격 유형을 가진 사람들은 짜증이 날 수 있습니다.',
        Chdescriptsion3_2: '',
        typetext3: '토론자는 항상 어떤 주제에 대해서도 좋은 토론을 하기 위해 준비하고 있지만, 토론자는 종종 더 감정적인 폭발과 논쟁을 관리하는 데 파트너의 도움이 필요합니다. 토론자들은 대부분의 사람들보다 더 유능하지만, 목소리 갈등에 관해서는 그들에게도 한계와 규칙이 있습니다.',
        Chdescriptsion3_3: '',
        Characteristic4: '더 나은 방법 찾기',
        Chdescriptsion4_1: '운 좋게도 토론자 성격은 무엇이 문제인지 인식합니다. 그들은 자녀가 똑똑하고 독립적이며 정직한 성인으로 성장하기를 원합니다. 이러한 가치를 전달하기 위해 토론자는 다른 토론과 마찬가지로 모든 측면에서 접근할 수 있는 용어로 의사 소통해야 한다는 것을 알고 있습니다. 그것이 감정 표현과 호소의 도구를 사용하는 방법을 배우는 것을 의미한다면, 그렇게 함으로써 실제적이고 개인적인 용어로도 감정 표현을 더 많이 하게 되는 것입니다.',
        Chdescriptsion4_2: '',
    
    },{
        id: '5',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '“내 본능은 내 아이들을 고통으로 보호하는 것입니다. 그러나 역경은 종종 우리에게 성격과 중추를 주는 것입니다.”',
        footer: '니콜 키드먼',
        description: '부모로서 옹호자(INFJ)는 자신에게 중요한 것에 대한 명확한 비전을 가지고 있습니다. 즉, 자녀를 독립적이고 만능의 좋은 사람으로 키우는 것입니다. 옹호인은 자신의 책임을 진지하게 생각하며, 부모가 된다면 어떻게 하면 자녀의 삶과 경험을 긍정적으로 형성할 수 있을지 깊이 생각합니다.',
        Characteristic1: '',
        Chdescriptsion1_1: '부모가 되는 것은 쉽지 않지만, 그렇게 되기를 기대하는 옹호자는 거의 없습니다. 이들은 인생에서 가장 가치 있는 일 중 많은 부분이 가장 어려운 일이기도 하다는 것을 알고 있습니다. 즉, 옹호자들이 자녀 양육의 매일의 고군분투 속에서 기쁨과 성취감을 유지하는 데 도움이 되는 사고 방식입니다.',
        Chdescriptsion1_2: '',
        typetext1: '여러 면에서 양육을 통해 옹호자는 자신이 사랑하는 사람에 대해 느끼는 창의성, 연민, 헌신의 놀라운 힘을 포함하여 자신의 장점을 훌륭하게 활용할 수 있습니다.',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '나처럼 독특해지기',
        Chdescriptsion2_1: '자상하고 충성스러운 Advocate 부모는 자녀의 삶을 개선하기 위해 필요한 모든 일을 기꺼이 합니다. 그러나 이러한 성격 유형을 가진 부모가 고집이 센 부모라고 생각하면 오산입니다. 사실, 옹호자들은 아주 엄격할 수 있습니다. 왜냐하면 장기적으로 자녀의 인격을 구축하려는 그들의 헌신이 일시적인 고려 사항(예: 자녀에게 짜증을 멈추는 데 도움이 되는 사탕을 주는 것과 같은 것)보다 중요하지 않기 때문입니다.',
        Chdescriptsion2_2: 'Advocates는 자녀 양육에 많은 선물을 제공하지만 완벽한 부모는 없다는 사실을 기억하는 것이 중요합니다.',
        typetext2: '때때로 Advocates는 각 어린이의 성격이나 발달 단계를 고려하지 않은 비현실적인 기준을 자녀에게 적용할 수 있습니다.',
        Chdescriptsion2_3: '예를 들어, 그들은 자녀가 자신에게 기대하는 것과 동일한 성실성과 정직성을 보여주기를 기대하고, 자녀가 관대하지 않거나 비윤리적이라고 인식하는 방식으로 행동할 때마다 당황하게 됩니다. 또는 자녀가 외부 구조와 지도를 갈망하는 경우 약함의 표시로 간주하여 자녀를 독립적이고 창의적이며 독특하게 만들 수 있습니다.',
        Characteristic3: '',
        Chdescriptsion3_1: '옹호하는 부모는 무의식적으로 자신의 신념과 가치를 자녀에게 많이 투영할 수 있습니다.',
        Chdescriptsion3_2: '아이에게 이러한 모든 기대는 모순되고 성취하기 불가능하게 느껴질 수 있습니다. 그리고 아이의 성격과 발달 단계에 따라 이러한 기대는 실제로 성취 가 불가능할 수도 있습니다. 청소년기에 아이들은 이러한 표준을 무시하거나 옹호자 부모의 가치에 반하는 신념을 지지함으로써 반항할 수 있습니다. 이러한 상황에서 옹호자는 자녀가 자신을 비판하거나 거부하고 있다고 느낄 수 있습니다. 이는 민감한 성격 유형에게 해로운 일입니다.',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '잘한 일',
        Chdescriptsion4_1: '옹호자들은 자녀들이 옳고 그름의 차이에 대한 확고한 이해를 갖고 자랄 수 있도록 노력합니다. 이러한 성격 유형을 가진 부모는 자녀가 자신이 믿는 대의와 최선을 다하기 위해 싸우도록 격려합니다. 자녀가 나이에 관계없이 옹호자는 단순히 자녀가 자신에게 진실하는 법을 배우도록 돕는 것만으로도 많은 성취감과 의미를 찾을 수 있습니다.',
        Chdescriptsion4_2: '궁극적으로 Advocate 부모는 자녀가 예상과 다르게 나타나는 경우 실패의 징후가 아님을 깨닫는 경향이 있습니다. 오히려 자신의 이상을 형성할 수 있는 능력을 가진 사람을 성공적으로 키웠다는 신호로 여기게 된다. 옹호자의 자녀들은 자라면서 특히 나이가 들면서 독립성과 성실성을 겸비한 것을 인정하게 되는 경우가 많습니다.',
    
    },{
        id: '6',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '중재자(INFP)에게 인생은 여정입니다. 그러나 그들은 세상을 통해 자신만의 길을 찾을 때에도 다른 사람들이 의미, 성취, 행복을 향한 여정을 시작하도록 도와야 한다는 부름을 느낍니다. 절제되고 지배적이지 않은 방식으로 중재자는 다른 사람들이 배우고 성장하도록 인도하는 것을 좋아합니다. 그리고 부모가 되는 것은 바로 그렇게 할 수 있는 믿을 수 없을 정도로 보람 있는 기회가 될 수 있습니다.',
        Chdescriptsion1_2: '중재자 부모는 처음부터 따뜻하고 배려하며 열린 마음을 목표로 합니다. 이 성격 유형을 가진 사람들은 아이들이 세상을 바라보는 눈이 휘둥그레지는 것을 기뻐하며, 아이들에게 자유를 주고 싶어 합니다. 즉, 자신의 의견을 형성하고, 자신의 관심사를 발견하고, 자신만의 독특한 자아로 성장할 수 있는 자유입니다. 중재자 부모는 자녀가 자신이 얼마나 사랑받는지 잊지 않기를 바라는 마음으로 지지와 수용의 안정적인 기반을 만들어 이러한 자유의 균형을 유지합니다.',
        typetext1: '민감하고 예리한 중재자는 자녀의 필요와 관점에 맞춰 조정합니다. 그들은 자녀를 자신의 투영물이 아니라 독특하고 다차원적인 개인으로 알고 싶어합니다.',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '도전에 대처하기',
        Chdescriptsion2_1: '중재자는 자유로운 영혼을 키우는 것을 즐길 수 있지만 그렇다고 해서 완전히 손을 떼는 것은 아닙니다. 그들은 정직, 연민 및 다른 사람을 돌보는 것의 중요성을 포함하여 자녀에게 핵심 가치를 가르치기를 원합니다. 그들은 또한 자녀가 특히 다른 사람을 해치지 않는 것과 관련하여 개인적인 책임의 의미를 이해하기를 바랍니다.',
        Chdescriptsion2_2: '모든 성격 유형의 부모와 마찬가지로 중재자 부모는 필연적으로 도전에 직면합니다. 그들은 양육 책임을 진지하게 받아들이기 때문에 자녀가 크고 작은 방식으로 잘못 행동하면 개인적인 실패처럼 느껴질 수 있습니다. 이러한 성격은 자녀들이 사려 깊지 않거나 윤리적이지 않은 방식으로 행동하는 것을 볼 때 특히 화를 낼 수 있습니다.',
        typetext2: '과도한 양심을 가진 중재자는 자녀의 잘못된 행동이 합리적이지 않거나 생산적이지 않은 경우에도 자신을 비난할 수 있습니다.',
        Chdescriptsion2_3: '자녀가 잘못된 행동을 할 때 중재자는 "내가 부모로서 실패했나요?" 여기서 위험은 이 성격 유형을 가진 사람들이 자신을 비난하는 데 너무 집중하여 자녀의 행동에 적절한 결과를 설정하지 않을 수 있다는 것입니다. 징계는 중재자에게 쉽게 주어지지 않을 수 있지만, 배려하고 부드러운 본성과 균형을 이룰 때 자녀에게 옳고 그름을 구별하는 것을 가르치는 사명에서 강력한 도구가 될 수 있습니다.',
        Characteristic3: '자발성으로 균형을 이루는 구조',
        Chdescriptsion3_1: '중재자 부모는 자연스럽게 좋은 역할 모델이 되기를 원합니다. 그들은 문제, 부정적인 감정, 좌절감을 숨기고 자녀에게 자신의 가장 좋은 면을 보여주려고 노력합니다. 이렇게 하면 가정의 화목함을 유지할 수 있고 자녀가 안전하고 보살핌을 받는다는 느낌을 받을 수 있습니다. 같은 이유로 중재자는 종종 세상의 더 큰 문제로부터 자녀를 보호하려고 노력합니다. 이것은 자녀가 어렸을 때 확실히 적절하지만 결국 중재자는 자녀와 함께 더 어려운 문제를 해결하는 방법을 찾아야 합니다.',
        Chdescriptsion3_2: '이러한 성격 유형을 가진 많은 부모가 겪는 또 다른 장애물은 자녀를 위한 실용적이고 일상적인 구조와 규칙을 수립하는 것입니다.',
        typetext3: '중재자는 자녀의 호기심과 열정을 억누르지 않으면서 창의적 에너지를 사용하여 경계를 부과할 수 있습니다. ',
        Chdescriptsion3_3: '이 부모들은 다른 사람의 입장이 되어 보는 놀라운 능력을 가지고 있으며, 이를 통해 자녀의 개별적인 필요에 진정으로 적합한 일정과 규칙을 세울 수 있습니다.',
        Characteristic4: '',
        Chdescriptsion4_1: '구조와 자발성의 균형을 맞출 때 중재자는 자녀가 가장 보살피고 책임감 있고 즐거운 자아로 성장할 수 있도록 도울 수 있습니다. 그리고 그것이 바로 이 부모들이 자신의 독특한 재능과 재능을 인식하고 그것을 세상과 공유할 수 있는 자녀를 키우기 위해 노력하는 것입니다.',
        Chdescriptsion4_2: '',
    
    },{
        id: '7',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '',
        Chdescriptsion1_2: '',
        typetext1: '',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '',
        Chdescriptsion2_1: '',
        Chdescriptsion2_2: '',
        typetext2: '',
        Chdescriptsion2_3: '',
        Characteristic3: '',
        Chdescriptsion3_1: '',
        Chdescriptsion3_2: '',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '1',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '',
        Chdescriptsion1_2: '',
        typetext1: '',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '',
        Chdescriptsion2_1: '',
        Chdescriptsion2_2: '',
        typetext2: '',
        Chdescriptsion2_3: '',
        Characteristic3: '',
        Chdescriptsion3_1: '',
        Chdescriptsion3_2: '',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '1',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '',
        Chdescriptsion1_2: '',
        typetext1: '',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '',
        Chdescriptsion2_1: '',
        Chdescriptsion2_2: '',
        typetext2: '',
        Chdescriptsion2_3: '',
        Characteristic3: '',
        Chdescriptsion3_1: '',
        Chdescriptsion3_2: '',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '1',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '',
        Chdescriptsion1_2: '',
        typetext1: '',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '',
        Chdescriptsion2_1: '',
        Chdescriptsion2_2: '',
        typetext2: '',
        Chdescriptsion2_3: '',
        Characteristic3: '',
        Chdescriptsion3_1: '',
        Chdescriptsion3_2: '',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '1',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '',
        Chdescriptsion1_2: '',
        typetext1: '',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '',
        Chdescriptsion2_1: '',
        Chdescriptsion2_2: '',
        typetext2: '',
        Chdescriptsion2_3: '',
        Characteristic3: '',
        Chdescriptsion3_1: '',
        Chdescriptsion3_2: '',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '1',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '',
        Chdescriptsion1_2: '',
        typetext1: '',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '',
        Chdescriptsion2_1: '',
        Chdescriptsion2_2: '',
        typetext2: '',
        Chdescriptsion2_3: '',
        Characteristic3: '',
        Chdescriptsion3_1: '',
        Chdescriptsion3_2: '',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '1',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '',
        Chdescriptsion1_2: '',
        typetext1: '',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '',
        Chdescriptsion2_1: '',
        Chdescriptsion2_2: '',
        typetext2: '',
        Chdescriptsion2_3: '',
        Characteristic3: '',
        Chdescriptsion3_1: '',
        Chdescriptsion3_2: '',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '1',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '',
        Chdescriptsion1_2: '',
        typetext1: '',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '',
        Chdescriptsion2_1: '',
        Chdescriptsion2_2: '',
        typetext2: '',
        Chdescriptsion2_3: '',
        Characteristic3: '',
        Chdescriptsion3_1: '',
        Chdescriptsion3_2: '',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '1',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '',
        Chdescriptsion1_2: '',
        typetext1: '',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '',
        Chdescriptsion2_1: '',
        Chdescriptsion2_2: '',
        typetext2: '',
        Chdescriptsion2_3: '',
        Characteristic3: '',
        Chdescriptsion3_1: '',
        Chdescriptsion3_2: '',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },{
        id: '1',
        url: '/intj.svg',
        title: '육아',
        Greatperson: '',
        footer: '',
        description: '',
        Characteristic1: '',
        Chdescriptsion1_1: '',
        Chdescriptsion1_2: '',
        typetext1: '',
        Chdescriptsion1_3: '',
        Chdescriptsion1_4: '',
        Characteristic2: '',
        Chdescriptsion2_1: '',
        Chdescriptsion2_2: '',
        typetext2: '',
        Chdescriptsion2_3: '',
        Characteristic3: '',
        Chdescriptsion3_1: '',
        Chdescriptsion3_2: '',
        typetext3: '',
        Chdescriptsion3_3: '',
        Characteristic4: '',
        Chdescriptsion4_1: '',
        Chdescriptsion4_2: '',
    
    },
    
]